### ISSUE TITLE
Add possibility to generate documentation/reuse documentation from modules

### ISSUE THREAD

**Issue by SuperFola** [ArkScript-lang/ArkDoc#7]
Currently our modules are created in C++, thus ArkDoc can not read the source code and add it to the documentation.

It would be useful if ArkDoc could use the Markdown files from `lib/ext/module_name/documentation/` and include them in the generated html documentation.

**Comment by PierrePharel** [comment]
yes, good idea 🤔

**Comment by PierrePharel** [comment]
But, C++ syntax support comming soon 🤔

**Comment by rakista112** [comment]
> But, C++ syntax support coming soon 🤔

Oh there's work been done on it already? For ArkDoc?

**Comment by SuperFola** [comment]
Now we can say we have support for it, in the upcoming version of ArkDoc
